name: planify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_ml_model_downloader: ^0.3.3+4
  mockito: ^5.4.6

  google_mlkit_smart_reply: ^0.13.0 
  google_mlkit_commons: ^0.11.0 
  mysql1: ^0.20.0

  http: ^1.2.0 

  carousel_slider: ^4.2.1 
  percent_indicator: ^4.2.3 
  intl: ^0.20.2 
  file_picker: ^8.0.0+1 
  image_picker: ^1.1.0 
  flutter_svg: ^2.1.0 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ 
    - assets/fonts/ 
    - assets/astronaut.png 

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow-ExtraBold.ttf 
        - asset: assets/fonts/Barlow-SemiBold.ttf 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
          weight: 300
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf # Adapte o caminho e o nome do arquivo
    - family: NotoColorEmoji # Se você precisar de suporte a emojis coloridos
      fonts:
        - asset: fonts/NotoColorEmoji.ttf 