name: planify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Garanta que seu SDK seja compatível com Flutter 3.x

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # <-- ESSA LINHA É CRÍTICA PARA LOCALIZAÇÕES
    sdk: flutter

  # Firebase Core e outras bibliotecas do Firebase
  firebase_core: ^2.28.0 
  cloud_firestore: ^4.17.0 
  firebase_auth: ^4.19.0 
  firebase_ml_model_downloader: ^0.2.0+6 

  # Google ML Kit Smart Reply e Commons
  google_mlkit_smart_reply: ^0.11.0 
  google_mlkit_commons: ^0.6.0 

  # HTTP
  http: ^1.2.0 

  # UI e outras utilidades
  carousel_slider: ^4.2.1 
  percent_indicator: ^4.2.3 
  intl: ^0.20.2 # ALINHADO COM flutter_localizations. MUITO IMPORTANTE!
  file_picker: ^8.0.0+1 
  image_picker: ^1.1.0 
  flutter_svg: ^2.0.10+1 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/ # Certifique-se que esta pasta existe e tem as fontes
    - assets/astronaut.png # <--- Nome do arquivo que você tem

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Light.ttf # <--- Nome do arquivo que você tem
          weight: 300