name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
    shelf: ^1.3.0
shelf_router: ^1.0.0
mysql1: ^0.18.1
json_serializable: ^6.0.0
shelf_cors: ^0.1.0
convert: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
